config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :bookings, only: [:index, :show, :edit, :update, :destroy]
  resources :posters, only: [:index, :show, :create, :new] do
    resources :bookings, only: [:new, :create]
  end
  get "/booking_confirmation/:id", to: "bookings#booking_confirmation", as: "booking_confirmation"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :poster
  belongs_to :user
end

app/models/poster.rb
class Poster < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  validates :photo, presence: true

  include PgSearch::Model


  pg_search_scope :search_by_band_name_and_description,
                  against: [:band_name, :description],
                  using: {
                    tsearch: { prefix: true }
                  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :owner])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :owner])
  end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings_user = Booking.where(user: current_user)
    @bookings = Booking.all
  end

  def new
    @booking = Booking.new
    @poster = Poster.find(params[:poster_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @poster = Poster.find(params[:poster_id])
    @booking.poster = @poster

    if @booking.save
      redirect_to booking_confirmation_path(@booking)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  def update
    # If statement for status, ALWAYS TRUE OR FALSE
    set_booking
    @booking.status = true
    @booking.save!
    redirect_to booking_path(@booking)
  end

    def show
      @booking = Booking.find(params[:id])
    end

    def booking_confirmation
      set_booking
      @poster = @booking.poster
      @final_price = @poster.price_per_day * (@booking.checkout_on - @booking.checkin_on)
    end

    private

    def set_booking
      @booking = Booking.find(params[:id])
    end

  def total_price
    @poster = Poster.find(params[:id])
    @total_days = (@booking.checkout_on - @booking.checkin_on).to_i
    @total_price = total_days * @booking.price_per_day
  end

  def booking_params
    params.require(:booking).permit(:checkin_on, :checkout_on, :value, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/posters_controller.rb
class PostersController < ApplicationController
  def index
    @posters = Poster.all
    if params[:query].present?
      @posters = Poster.search_by_band_name_and_description(params[:query])
    end
  end

  def new
    @poster = Poster.new
  end

  def show
    @poster = Poster.find(params[:id])
  end

  def create
    @poster = Poster.create(poster_params)
    @poster.user = current_user
    if @poster.save
      redirect_to poster_path(@poster)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def poster_params
    params.require(:poster).permit(:band_name, :description, :price_per_day, :height, :width, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/booking_confirmation.html.erb
<style>
  .custom-card {
    font-family: Arial, sans-serif;
  }
</style>

<div class="card mb-3 custom-card" style="max-width: 1000px;">
  <div class="row g-0">
    <div class="col-md-6">
      <%= image_tag @booking.poster.photo, class: "img-thumbnail rounded float-right", style: "max-width: 100%; height: auto;" %>
    </div>
    <div class="col-md-6" style="background-color: pink;" >
      <div class="card-body">
        <h1 class="card-title" style="font-size: 2rem; font-weight: bold;">Your Booking is Confirmed! 🎉</h1>
        <h3 class="card-subtitle mb-2"><%= @booking.poster.band_name %></h3>
        <p class="card-text"><%= @poster.description %></p>
        <h3 class="card-title">Final Price:</h3>
        <h3 class="card-title"><%= @final_price %>$</h3>
        <%= link_to 'Back to Bookings', bookings_path, class: 'btn btn-secondary btn-sm mt-3' %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="text-center padded">
<h1 class="mt-4 page-title">Rental Requests</h1>

<table class="table table-bordered mt-3">
  <thead class="thead-dark">

    <tr>
      <th>Renter</th>
      <th>Poster</th>
      <th>Start-Date</th>
      <th>End-Date</th>
      <th>Value</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.user.first_name %></td>
        <td><%= booking.poster.band_name %>
            <%= image_tag booking.poster.photo, class: "img-thumbnail align-right", size: "40x20", style: "float: right;"%></td>
        <td><%= booking.checkin_on %></td>
        <td><%= booking.checkout_on %></td>
        <% if booking.checkin_on.present? && booking.checkout_on.present? %>
        <td><%= number_to_currency(booking.poster.price_per_day * (booking.checkout_on - booking.checkin_on), unit: 'CAD') %></td>
        <% else %>
        <td>N/A</td>
        <% end %>

        <td>
          <% if booking.status.nil?  %>
            Pending
          <% elsif booking.status == true  %>
            Confirmed
          <% else %>
            Rejected
          <% end %>
        <td>
        <% unless booking.status  %>
          <%= link_to 'Confirm', booking_path(booking), data: { "turbo-method": :patch } , class: 'btn btn-success btn-sm mr-1' %>
          <%= link_to 'Decline', booking_path(booking), data: { "turbo-method": :delete, confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
        <% end %>
        </td>
      </tr>

    <% end %>
  </tbody>
</table>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="text-center padded">
    <h1>Rental request details:</h1>
  </div>

  <div class="mx-auto col-8">
    <%= form_with model: @booking, url: poster_bookings_path(@poster), method: :post, class: "form" do |form| %>
      <div class="form-group mb-4">
        <%= form.label :book_this_poster_from, class: "control-label" %>
        <%= form.date_field :checkin_on, class: "form-control"%>
      </div>

      <div class="form-group mb-4">
        <%= form.label :to, class: "control-label" %>
        <%= form.date_field :checkout_on, class: "form-control"%>
      </div>

      <div class="form-group mb-4">
        <%= form.label :address_to_send_the_poster, class: "control-label" %>
        <%= form.text_field :value, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.submit "Send request", class: "btn btn-flat" %>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<style>
  .custom-card {
    font-family: Arial, sans-serif;
  }
</style>

<div class="card mb-3 custom-card" style="max-width: 1000px;">
  <div class="row g-0">
    <div class="col-md-6">
      <%= image_tag @booking.poster.photo, class: "img-thumbnail rounded float-right", style: "max-width: 100%; height: auto;" %>
    </div>
    <div class="col-md-6" style="background-color: pink;" >
      <div class="card-body">
        <h1 class="card-title" style="font-size: 2rem; font-weight: bold;">Congrats! Your booking is confirmed </h1>
        <h3 class="card-subtitle mb-2"><%= @booking.poster.band_name %></h3>
        <p class="card-text"><%= @booking.poster.description %></p>
        <p><strong>Start-Date:</strong> <%= @booking.checkin_on %></p>
        <p><strong>End-Date:</strong> <%= @booking.checkout_on %></p>
        <%= link_to 'Back to bookings', bookings_path, class: 'btn btn-secondary btn-sm' %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoyBandPosters</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&family=EB+Garamond&family=Handjet:wght@600&family=Noto+Sans+JP:wght@200&display=swap');
    </style>

  </head>

  <body>
  <%= render '/components/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.8),rgba(0,0,0,0.2)), url(https://wallpapers.com/images/hd/cute-bts-group-lined-up-in-pastel-colors-keu8km5u1209cmfy.jpg">
      <div class="container">
        <h1 class="home-title shimmer">Welcome to BOY BAND POSTERS!</h1>

        <h2>Made for poster aficionados</h2>
        <h6 id="description">Find vintage posters<br>
                            <br>
                            MAKE $$ - list your poster!</h6>
      </div>
    </div>
<%#
<p class="shimmer">Shimmering Word</p>
<img src="https://i.stack.imgur.com/MeQxk.png"class="shimmer" /> %>

    <div class="marquee-track">
      <hr>
        <container class="marquee-container">
          <marquee>
            <pre id="marquee">ABBA   |   BACKSTREET BOYS   |   THE BEATLES   |   BTS   |   HANNAH MONTANNA   |   JONAS BROTHERS   |   NSYNC   |   ONE DIRECTION   |   SPICE GIRLS</pre>
          </marquee>
        </container>
      <hr>
    </div>

app/views/posters/_form.html.erb
<div class="mx-auto col-6">
  <%= simple_form_for(poster) do |f| %>
  <h1 class="page-title">Your poster's details:</h1>
    <%= f.input :band_name %>
    <%= f.input :description %>
    <%= f.input :price_per_day %>
    <%= f.input :height %>
    <%= f.input :width %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: "poster-button" %>
  <% end %>
</div>

app/views/posters/index.html.erb
<h1 class="page-title"><i class="fa-solid fa-arrow-pointer"></i> Click & pick:</h1>

<div class="container">

  <div class="row justify-content-center">
    <div class="col-sm-8 my-3">
      <%= form_with url: posters_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Type your favourite boy band..."
        %>
        <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="poster-index">
  <% @posters.each do |poster| %>
    <%= link_to poster_path(poster) do %>
      <div class="card-product">
        <%= cl_image_tag poster.photo.key %>
        <div class="card-product-infos">
          <h1 class="card-title">
          <%= poster.band_name %>
          </h1>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

<%# INFO: The code below is for references only. Delete when no longer needed. %>
<%# if poster.photo.attached? %>
  <%# cl_image_tag poster.photo.key, height: 400, width: 250, crop: :fill %>
<%# end %>

app/views/posters/new.html.erb
<%# This belongs to _form.html.erb %>
<%= render "form", poster: @poster %>

app/views/posters/show.html.erb
<div class="show-container">
  <h1 class="show-title" style="margin-left: 10px; font-family: handjet; font-size: 90px;"><%= @poster.band_name %></h1>
  <div class="row">
    <%= image_tag @poster.photo, class: "col-4 show-image"%>
    <div class="col-8" id="show-details">
      <h3><i class="fa-solid fa-circle-info"></i> <%= @poster.description %></h3>
      <h3><i class="fa-solid fa-dollar-sign"></i> <%= @poster.price_per_day %></h3>
      <h3><i class="fa-solid fa-up-down"></i> cm <%= @poster.height %></h3>
      <h3><i class="fa-solid fa-arrows-left-right"></i> cm <%= @poster.width %></h3>

      <%= link_to "Request to rent poster!", new_poster_booking_path(@poster), class: "btn btn-flat" %>

    </div>
  </div>
</div>


<%# style=" max-height: 600px; max-width: 400px; object-fit: cover; margin-left: 25px; %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>